### ISSUE TITLE
Failed to activate the dash-on-cursor package

### ISSUE THREAD

**Issue by sroberts** [stanaka/dash-on-cursor#4]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.194.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.2
**Thrown From**: [dash-on-cursor](https://github.com/stanaka/dash-on-cursor) package, v0.1.0

### Stack Trace

Failed to activate the dash-on-cursor package

```
At Cannot read property 'command' of undefined

TypeError: Cannot read property 'command' of undefined
    at Object.module.exports.activate (/Users/sroberts/.atom/packages/dash-on-cursor/lib/dash-on-cursor.coffee:30:32)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:418:29
    at Config.module.exports.Config.transact (/Applications/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:413:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/Atom.app/Contents/Resources/app.asar/src/package-manager.js:394:46)
```

### Commands

```
```

### Config

```json
{
  "core": {}
}
```

### Installed Packages

```coffee
# User
Rdio, v0.5.1
autocomplete-plus, v2.12.0
dash-on-cursor, v0.1.0
file-icons, v1.5.4
go-plus, v3.3.6
jsonlint, v1.1.0
linter, v0.12.1
linter-pyflakes, v0.0.4
linter-write-good, v0.4.2
regex-railroad-diagram, v0.7.4

# Dev
No dev packages
```

**Comment by rtremmel** [comment]
+1

**Comment by inferst** [comment]
+1

**Comment by iiechapman** [comment]
Does anyone know if the original developer is still maintaining this package?
I fixed the issue, but it looks like nothing has happened here for a couple of years.

**Comment by steakknife** [comment]
`apm install iiechapman/dash-on-cursor`
